import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class DashboardNextDnsTest(unittest.TestCase):
    def test_dashboard_consumes_generated_summary_only(self):
        html = (ROOT / "viz" / "index.html").read_text()

        self.assertIn('const NEXTDNS_URL = "./nextdns_summary.json";', html)
        self.assertIn('fetch(NEXTDNS_URL, { cache: "no-store" })', html)
        self.assertIn('id="dnsQueries"', html)
        self.assertIn('id="dnsEncrypted"', html)
        self.assertIn('id="dnsTopQueried"', html)
        self.assertIn('id="dnsTopQueriedCount"', html)
        self.assertIn('id="dnsTopBlocked"', html)
        self.assertIn('id="dnsTopBlockedCount"', html)
        self.assertIn('id="dnsUnavailable"', html)
        self.assertIn('id="dnsActivitySummary"', html)
        self.assertIn("DNS Activity", html)
        self.assertNotIn("api.nextdns.io", html)
        self.assertNotIn("X-Api-Key", html)
        self.assertNotIn("NEXTDNS_API_KEY", html)
        self.assertIn('class="metric-pair dns-domain-pair"', html)
        self.assertIn('class="dns-domain-text" id="dnsTopQueried"', html)
        self.assertIn('class="dns-domain-count" id="dnsTopBlockedCount"', html)
        self.assertIn('class="detail-line dns-domain-detail-line"', html)
        self.assertIn('id="mobileDnsTopQueriedCount"', html)
        self.assertIn('id="mobileDnsTopBlockedCount"', html)
        self.assertIn('id="mobilePrimaryDnsCard"', html)
        self.assertIn('id="mobilePrimaryDnsTopQueried"', html)
        self.assertIn('id="mobilePrimaryDnsTopBlocked"', html)
        self.assertIn("function renderDomainWithCount(domainId, countId, domain, count, noun)", html)
        self.assertIn('el.title = cleanDomain;', html)
        self.assertIn('renderDomainWithCount("dnsTopQueried", "dnsTopQueriedCount", summary.top_queried_domain, summary.top_queried_domain_count, "queries");', html)
        self.assertIn('renderDomainWithCount("dnsTopBlocked", "dnsTopBlockedCount", summary.top_blocked_domain, summary.top_blocked_domain_count, "blocks");', html)
        self.assertIn('renderDomainWithCount("mobileDnsTopQueried", "mobileDnsTopQueriedCount", summary.top_queried_domain, summary.top_queried_domain_count, "queries");', html)
        self.assertIn('renderDomainWithCount("mobileDnsTopBlocked", "mobileDnsTopBlockedCount", summary.top_blocked_domain, summary.top_blocked_domain_count, "blocks");', html)

    def test_dashboard_explains_heatmap_and_chart_semantics(self):
        html = (ROOT / "viz" / "index.html").read_text()

        self.assertIn("Composite WAN evidence: internet + resolver probes", html)
        self.assertIn('renderHeatmap("#heatmap", currentVizState.compositeWanBuckets)', html)
        self.assertIn("function buildCompositeWanBuckets", html)
        self.assertIn('getNoticeabilitySummary([...internetSeriesMarked, ...resolverSeriesMarked]', html)
        self.assertIn("Internet degraded", html)
        self.assertIn("Resolver degraded", html)
        self.assertIn("dark gray = sustained p95/jitter/loss degradation", html)
        self.assertIn("line = p95 latency only", html)
        self.assertIn("Raw reasons: p95", html)
        self.assertIn("Selected Bucket", html)
        self.assertIn("selectedBucket: currentVizState.selectedBucket", html)
        self.assertIn("WAN resolver, and LAN gateway charts", html)
        self.assertNotIn("Internet probes only", html)
        self.assertNotIn("Number(k)", html)

    def test_dashboard_ux_copy_uses_clearer_local_loading_and_selection_states(self):
        html = (ROOT / "viz" / "index.html").read_text()

        self.assertIn("Loading latest telemetry", html)
        self.assertIn("Investigation history", html)
        self.assertIn("No selection", html)
        self.assertIn("Choose a heatmap bucket to pin the same interval across all three charts.", html)
        self.assertIn("Details", html)
        self.assertIn("Top queried", html)
        self.assertIn("Top blocked", html)
        self.assertIn("Router path", html)
        self.assertNotIn(">Connection<", html)
        self.assertIn("Last sample:", html)
        self.assertIn("Refresh:", html)
        self.assertIn("Window:", html)
        self.assertIn("Live", html)
        self.assertIn("Delayed", html)
        self.assertIn("Offline", html)
        self.assertIn("Good", html)
        self.assertIn("Notice", html)
        self.assertIn("Poor", html)
        self.assertIn("Selected time window", html)
        self.assertIn("Click a bucket to pin a 15-minute interval.", html)
        self.assertIn("review that same 15-minute interval across the evidence chips and all three charts", html)
        self.assertIn("Why This Interval", html)
        self.assertIn('id="clearSelectionButton"', html)
        self.assertIn("Clear selection", html)
        self.assertIn("Investigation history (selected)", html)
        self.assertIn("Open investigation history for this interval", html)
        self.assertIn('window.addEventListener("keydown", ev => {', html)
        self.assertIn('ev.key === "Escape"', html)
        self.assertIn('attr("tabindex", 0)', html)
        self.assertIn('attr("role", "button")', html)
        self.assertIn('attr("aria-pressed"', html)
        self.assertIn('function buildInvestigationHref(bucket)', html)
        self.assertIn("<h1>Prime Observer</h1>", html)
        self.assertIn('role="status" aria-live="polite" aria-atomic="true"', html)
        self.assertIn('setAttribute("aria-label", bucket ? "Open investigation history for the selected interval" : "Open investigation history")', html)
        self.assertIn('setAttribute("aria-label", bucket ? "Open investigation history for this interval" : "Open investigation history")', html)
        self.assertIn('role="img" aria-labelledby="wanInternetHeading wanInternetLegend"', html)
        self.assertIn('role="group" aria-labelledby="heatmapHeading heatmapLegend"', html)
        self.assertIn('svg [role="button"]:focus-visible', html)
        self.assertIn("View DNS activity >", html)
        self.assertIn("Hide DNS activity", html)
        self.assertNotIn(">Telemetry<", html)
        self.assertNotIn("Collector healthy", html)
        self.assertNotIn("Collector delayed", html)
        self.assertNotIn("Collector stalled", html)

    def test_dashboard_header_replaces_data_freshness_card(self):
        html = (ROOT / "viz" / "index.html").read_text()

        self.assertIn('id="statusState"', html)
        self.assertIn('id="statusLastSample"', html)
        self.assertIn('id="statusRefresh"', html)
        self.assertIn('id="statusWindow"', html)
        self.assertIn('id="statusDot"', html)
        self.assertIn('document.getElementById("statusRefresh").textContent = `every ${REFRESH_MS / 1000}s`;', html)
        self.assertIn('document.getElementById("statusWindow").textContent = `last ${WINDOW_HOURS}h`;', html)
        self.assertIn('summaryEl.textContent = "unavailable";', html)
        self.assertIn('summaryEl.textContent = summary;', html)

    def test_dashboard_renders_split_impact_and_application_experience(self):
        html = (ROOT / "viz" / "index.html").read_text()

        self.assertIn("User-facing impact", html)
        self.assertIn('id="observedImpactInline"', html)
        self.assertIn('id="mobileObservedImpactInline"', html)
        self.assertIn("DNS and web checks", html)
        self.assertIn('id="applicationExperienceCard"', html)
        self.assertIn('id="mobileApplicationExperienceCard"', html)
        self.assertIn('id="applicationSystemDnsValue"', html)
        self.assertIn('id="applicationPrimaryDnsValue"', html)
        self.assertIn('id="applicationSecondaryDnsValue"', html)
        self.assertIn('id="applicationHttpsValue"', html)
        self.assertIn("function renderApplicationExperience(application)", html)
        self.assertIn("System DNS", html)
        self.assertIn("Direct secondary resolver", html)
        self.assertNotIn("openrouter.ai/api/v1/chat/completions", html)
        self.assertIn('label = "Live";', html)
        self.assertIn("function toCompactRelativeAge(d){", html)
        self.assertIn('let summary = toCompactRelativeAge(last.t);', html)
        self.assertNotIn("Data Freshness", html)
        self.assertNotIn("telemetryBadge", html)
        self.assertNotIn("telemetryState", html)
        self.assertNotIn("telemetrySummary", html)
        self.assertNotIn("telemetryUpdated", html)
        self.assertNotIn("mobileTelemetryState", html)
        self.assertNotIn("mobileTelemetrySummary", html)
        self.assertNotIn("mobileTelemetryUpdated", html)

    def test_dashboard_keeps_same_primary_concepts_on_desktop_and_mobile(self):
        html = (ROOT / "viz" / "index.html").read_text()

        self.assertIn('class="row dashboard-overview primary-operator-row"', html)
        self.assertIn('class="row dashboard-overview local-evidence-row"', html)
        self.assertIn('class="mobile-state-grid"', html)
        self.assertIn('id="mobileTechnicalConditionValue"', html)
        self.assertIn('id="mobileUserImpactValue"', html)
        self.assertIn('id="mobileAffectedScopeValue"', html)
        self.assertIn('id="mobileLikelyCauseValue"', html)
        self.assertIn('id="supportingContextDetails"', html)
        self.assertIn('id="dnsCard"', html)
        self.assertIn('id="mobileDnsCard"', html)
        self.assertIn('id="mobilePrimaryDnsCard"', html)
        self.assertIn('id="mobileDnsDisclosure"', html)
        self.assertIn('id="mobileInternetConditionsCard"', html)
        self.assertIn('id="mobilePowerInfrastructureCard"', html)

    def test_dashboard_trust_repair_hides_internal_or_empty_primary_text(self):
        html = (ROOT / "viz" / "index.html").read_text()

        self.assertIn("plainFallbackHeadline(dimensions, dependency, refined)", html)
        self.assertIn("No user-facing failure was detected by current checks", html)
        self.assertIn('document.getElementById("userImpactCard").style.display = estimatedState ? "" : "none";', html)
        self.assertIn('document.getElementById("observedImpactInline").textContent = observedImpactDetail(observedImpact, feedback);', html)
        self.assertIn('document.getElementById("likelyCauseCard").style.display = attributionSubstantive ? "" : "none";', html)
        self.assertIn('document.getElementById("refinedAttributionCard").style.display = attributionSubstantive ? "" : "none";', html)
        self.assertIn("Likely issue is not yet localized", html)
        self.assertNotIn("No healthy comparison text emitted", html)
        self.assertNotIn("No action guidance emitted", html)
        self.assertNotIn("dependency member", html)
        self.assertNotIn("user_symptoms", html)
        self.assertNotIn("Unavailable from artifact", html)
        self.assertNotIn("Missing scope field", html)

    def test_dashboard_resolver_path_wording_is_operator_facing(self):
        html = (ROOT / "viz" / "index.html").read_text()

        self.assertIn("Active resolver", html)
        self.assertIn("Active resolver not established", html)
        self.assertIn("Resolver coverage", html)
        self.assertIn("Both monitored resolver paths remain reachable", html)
        self.assertIn("No healthy monitored resolver path", html)
        self.assertIn("Primary ${primaryState}, secondary ${secondaryState}", html)
        self.assertNotIn("Monitored redundancy", html)
        self.assertNotIn("Active member", html)
        self.assertNotIn("No dependency member evidence", html)

    def test_dashboard_supporting_context_remains_collapsed_and_available(self):
        html = (ROOT / "viz" / "index.html").read_text()

        self.assertIn('<details class="supporting-context" id="supportingContextDetails">', html)
        self.assertLess(html.index('id="supportingContextDetails"'), html.index('id="dnsCard"'))
        self.assertLess(html.index('id="supportingContextDetails"'), html.index('id="dependencyStateCard"'))
        self.assertLess(html.index('id="supportingContextDetails"'), html.index('id="refinedAttributionCard"'))
        self.assertIn("Cloudflare Radar", html)
        self.assertIn("Power Infrastructure", html)
        self.assertIn("Normal ASN traffic does not prove a measured path is healthy", html)
        self.assertIn('if (supportingContext) supportingContext.open = false;', html)

    def test_dashboard_primary_view_removes_duplicate_action_resolver_and_attribution_cards(self):
        html = (ROOT / "viz" / "index.html").read_text()
        primary = html[html.index('id="operatorAssessmentCard"'):html.index('id="supportingContextDetails"')]

        self.assertIn("User-facing impact", primary)
        self.assertIn("What is affected", primary)
        self.assertIn("Likely issue", primary)
        self.assertIn("DNS and web checks", primary)
        self.assertNotIn("Technical Condition", primary)
        self.assertNotIn("Estimated User Impact", primary)
        self.assertNotIn("Affected Scope", primary)
        self.assertNotIn("Likely Cause", primary)
        self.assertNotIn("Application Experience", primary)
        self.assertNotIn("Current Action", primary)
        self.assertNotIn("DNS Resolver Paths", primary)
        self.assertNotIn("Refined Attribution", primary)
        self.assertNotIn("Detection Confidence", primary)
        self.assertNotIn("Compare primary and secondary resolver paths", html)

    def test_investigation_view_renders_dns_context_without_api_access(self):
        html = (ROOT / "viz" / "investigate.html").read_text()

        self.assertIn("DNS Context", html)
        self.assertIn("data.dns_context", html)
        self.assertIn("Total queries", html)
        self.assertIn("Blocked", html)
        self.assertIn("operator_assistant_output.json", html)
        self.assertIn("Summary", html)
        self.assertIn('role="status" aria-live="polite" aria-atomic="true"', html)
        self.assertNotIn("api.nextdns.io", html)
        self.assertNotIn("X-Api-Key", html)
        self.assertNotIn("openrouter.ai/api/v1/chat/completions", html)


if __name__ == "__main__":
    unittest.main()
